In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import xlrd
import openpyxl

In [2]:
pd.read_excel('OA3.xlsx',sheet_name="Sheet1")

P1     P2     P3    P4     P5  Resultant Frequency  Return Loss  \
0   55.89  70.20  53.83  0.50  2.270                 2.58       -18.99   
1   55.89  58.50  49.07  0.37  1.515                 2.58       -10.89   
2   55.89  46.80  44.17  0.25  4.545                 2.32       -19.98   
3   55.89  35.10  39.26  0.75  3.790                 2.48       -18.94   
4   55.89  23.40  58.89  0.62  3.030                 2.66       -22.45   
5   46.57  70.20  49.07  0.25  3.790                 2.34       -14.96   
6   46.57  58.50  44.17  0.75  3.030                 2.56       -22.19   
7   46.57  46.80  39.26  0.62  2.270                 2.26        -8.08   
8   46.57  35.10  58.89  0.50  1.515                 2.32       -10.89   
9   46.57  23.40  53.83  0.37  4.545                 2.30       -29.79   
10  44.71  62.71  53.89  0.25  8.970                 2.43       -22.46   
11  44.71  57.12  49.39  0.37  8.220                 2.43       -19.72   
12  44.71  51.53  44.89  0.50  7.470                 2.43       -14.01   
13  44.71  45.94  40.39  0.62  6.720                 3.98       -28.34   
14  44.71  45.00  36.00  0.75  5.980                 5.06       -24.23   
15  39.12  62.71  49.39  0.50  6.720                 2.45       -10.59   
16  39.12  57.12  44.89  0.62  5.980                 2.45        -7.00   
17  39.12  51.53  40.39  0.75  8.970                 2.46        -7.41   
18  39.12  45.94  36.00  0.25  8.220                 2.54        -3.49   
19  39.12  40.35  53.89  0.37  7.470                 2.44       -32.66   
20  37.26  70.20  44.17  0.62  1.515                 2.30        -7.64   
21  37.26  58.50  39.26  0.50  4.545                 2.36       -23.70   
22  37.26  46.80  58.89  0.37  3.790                 2.36       -16.44   
23  37.26  35.10  53.83  0.25  3.030                 2.38       -14.39   
24  37.26  23.40  49.07  0.75  2.270                 2.40       -10.76   
25  33.53  62.71  44.89  0.75  8.220                 2.48        -7.53   
26  33.53  57.12  40.39  0.25  7.470                 2.48        -4.03   
27  33.53  51.53  36.00  0.37  6.720                 2.57        -2.80   
28  33.53  45.94  53.89  0.50  5.980                 2.46       -11.77   
29  33.53  40.35  49.39  0.62  8.970                 2.46       -17.39   
30  27.94  70.20  39.26  0.37  3.030                 2.42       -23.81   
31  27.94  62.71  40.39  0.37  5.980                 4.91       -34.12   
32  27.94  58.50  58.89  0.25  2.270                 2.40       -29.32   
33  27.94  57.12  36.00  0.50  8.970                 4.83       -20.66   
34  27.94  51.53  53.89  0.62  8.220                 2.50        -9.39   
35  27.94  46.80  53.83  0.75  1.515                 2.38        -8.91   
36  27.94  45.94  49.39  0.75  7.470                 2.50        -7.50   
37  27.94  40.35  44.89  0.25  6.720                 4.86       -15.08   
38  27.94  35.10  49.07  0.62  4.545                 2.44       -28.71   
39  27.94  23.40  44.17  0.50  3.790                 2.42       -23.69   
40  22.35  62.71  36.00  0.62  7.470                 2.63        -1.86   
41  22.35  57.12  53.89  0.75  6.720                 2.53        -5.15   
42  22.35  51.53  49.39  0.25  5.980                 2.54        -3.55   
43  22.35  45.94  44.89  0.37  8.970                 2.54        -3.81   
44  22.35  40.35  40.39  0.50  8.220                 2.55        -2.23   
45  18.63  70.20  58.89  0.75  4.545                 2.58       -12.70   
46  18.63  58.50  53.83  0.62  3.790                 2.54       -10.96   
47  18.63  46.80  49.07  0.50  3.030                 2.48       -11.80   
48  18.63  35.10  44.17  0.37  2.270                 2.48       -20.02   
49  18.63  23.40  39.26  0.25  1.515                 2.44       -24.93   

    Fitness Function  S/N ratio  
0              -0.13     17.720  
1              -0.13     17.720  
2               0.13     17.720  
3              -0.03     30.460  
4              -0.21     13.550  
5               0.11     19.

In [3]:
ant = pd.read_excel('OA3.xlsx',sheet_name="Sheet1")
print(ant.describe())

              P1         P2         P3         P4         P5  \
count  50.000000  50.000000  50.000000  50.000000  50.000000   
mean   35.394000  49.258000  46.978000   0.498000   5.251000   
std    11.134238  13.267866   7.017078   0.178589   2.488117   
min    18.630000  23.400000  36.000000   0.250000   1.515000   
25%    27.940000  40.350000  40.390000   0.370000   3.030000   
50%    35.395000  49.165000  46.980000   0.500000   5.262500   
75%    44.710000  58.500000  53.830000   0.620000   7.470000   
max    55.890000  70.200000  58.890000   0.750000   8.970000   

       Resultant Frequency  Return Loss  Fitness Function  S/N ratio  
count            50.000000    50.000000         50.000000  50.000000  
mean              2.685800   -15.234400         -0.236200  22.982240  
std               0.703789     8.798548          0.703655  13.207934  
min               2.260000   -34.120000         -2.610000  -8.333000  
25%               2.420000   -22.385000         -0.097500  17.720000

In [4]:
ant.values

array([[ 5.589e+01,  7.020e+01,  5.383e+01,  5.000e-01,  2.270e+00,
         2.580e+00, -1.899e+01, -1.300e-01,  1.772e+01],
       [ 5.589e+01,  5.850e+01,  4.907e+01,  3.700e-01,  1.515e+00,
         2.580e+00, -1.089e+01, -1.300e-01,  1.772e+01],
       [ 5.589e+01,  4.680e+01,  4.417e+01,  2.500e-01,  4.545e+00,
         2.320e+00, -1.998e+01,  1.300e-01,  1.772e+01],
       [ 5.589e+01,  3.510e+01,  3.926e+01,  7.500e-01,  3.790e+00,
         2.480e+00, -1.894e+01, -3.000e-02,  3.046e+01],
       [ 5.589e+01,  2.340e+01,  5.889e+01,  6.200e-01,  3.030e+00,
         2.660e+00, -2.245e+01, -2.100e-01,  1.355e+01],
       [ 4.657e+01,  7.020e+01,  4.907e+01,  2.500e-01,  3.790e+00,
         2.340e+00, -1.496e+01,  1.100e-01,  1.917e+01],
       [ 4.657e+01,  5.850e+01,  4.417e+01,  7.500e-01,  3.030e+00,
         2.560e+00, -2.219e+01, -1.100e-01,  1.917e+01],
       [ 4.657e+01,  4.680e+01,  3.926e+01,  6.200e-01,  2.270e+00,
         2.260e+00, -8.080e+00,  1.900e-01,  1.442e+01],


In [5]:
x=ant.drop(columns=['Resultant Frequency','Return Loss','Fitness Function','S/N ratio'])
y=ant['Resultant Frequency']
z=ant['Return Loss']
z

0    -18.99
1    -10.89
2    -19.98
3    -18.94
4    -22.45
5    -14.96
6    -22.19
7     -8.08
8    -10.89
9    -29.79
10   -22.46
11   -19.72
12   -14.01
13   -28.34
14   -24.23
15   -10.59
16    -7.00
17    -7.41
18    -3.49
19   -32.66
20    -7.64
21   -23.70
22   -16.44
23   -14.39
24   -10.76
25    -7.53
26    -4.03
27    -2.80
28   -11.77
29   -17.39
30   -23.81
31   -34.12
32   -29.32
33   -20.66
34    -9.39
35    -8.91
36    -7.50
37   -15.08
38   -28.71
39   -23.69
40    -1.86
41    -5.15
42    -3.55
43    -3.81
44    -2.23
45   -12.70
46   -10.96
47   -11.80
48   -20.02
49   -24.93
Name: Return Loss, dtype: float64

In [6]:
# predicting resultant frequency 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
model=LinearRegression()
model.fit(x,y)
p = model.predict([[1,2,5,4,8],[3,1,2,5,7]])
p

C:\Users\Sarthak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.37389919, 4.46961989])

In [7]:
# predicting return loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test = train_test_split(x,z,test_size=0.2)
model=LinearRegression()
model.fit(x,z)
p = model.predict([[55,69,54,0.75,4],[3,1,2,5,9]])
p

C:\Users\Sarthak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-14.91727525,  26.97403212])

In [8]:
# predicting resultant frequency
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
model=LinearRegression()
model.fit(X_train,y_train)
p1 = model.predict(X_test)
p = model.predict([[17,20,38,0.2,1.5],
                   [18,19,35,0.3,1.6],
                  [16,18,37,0.2,1.4],
                  [17.5,19.5,36,0.3,1.45],
                  [16.5,20,36.5,0.25,1.55]])
# print(X_test,p)
mse = mean_squared_error(y_test, p1)
print(mse)
p

1.0430457800374693


C:\Users\Sarthak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.55470712, 2.63294748, 2.56486432, 2.61213233, 2.60178686])

In [9]:
# predicting return loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
X_train,X_test,z_train,z_test = train_test_split(x,z,test_size=0.2)
model=LinearRegression()
model.fit(X_train,z_train)
p = model.predict(X_test)
p1 = model.predict([[17,20,38,0.2,1.5],
                   [18,19,35,0.3,1.6],
                  [16,18,37,0.2,1.4],
                  [17.5,19.5,36,0.3,1.45],
                  [16.5,20,36.5,0.25,1.55]])
# print(X_test,p)
mse = mean_squared_error(z_test, p)
print(mse)
p1

144.99580483181637


C:\Users\Sarthak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-19.79077367, -18.66246967, -19.84726011, -18.78396437,
       -18.9262859 ])

In [10]:
a=ant.drop(columns=['Resultant Frequency','Return Loss','Fitness Function','S/N ratio'])
b=ant.drop(columns=['P1','P2','P3','P4','P5','Fitness Function','S/N ratio'])
b

Resultant Frequency  Return Loss
0                  2.58       -18.99
1                  2.58       -10.89
2                  2.32       -19.98
3                  2.48       -18.94
4                  2.66       -22.45
5                  2.34       -14.96
6                  2.56       -22.19
7                  2.26        -8.08
8                  2.32       -10.89
9                  2.30       -29.79
10                 2.43       -22.46
11                 2.43       -19.72
12                 2.43       -14.01
13                 3.98       -28.34
14                 5.06       -24.23
15                 2.45       -10.59
16                 2.45        -7.00
17                 2.46        -7.41
18                 2.54        -3.49
19                 2.44       -32.66
20                 2.30        -7.64
21                 2.36       -23.70
22                 2.36       -16.44
23                 2.38       -14.39
24                 2.40       -10.76
25                 2.48        -7.53
26                 2.48        -4.03
27                 2.57        -2.80
28                 2.46       -11.77
29                 2.46       -17.39
30                 2.42       -23.81
31                 4.91       -34.12
32                 2.40       -29.32
33                 4.83       -20.66
34                 2.50        -9.39
35                 2.38        -8.91
36                 2.50        -7.50
37                 4.86       -15.08
38                 2.44       -28.71
39                 2.42       -23.69
40                 2.63        -1.86
41                 2.53        -5.15
42                 2.54        -3.55
43                 2.54        -3.81
44                 2.55        -2.23
45                 2.58       -12.70
46                 2.54       -10.96
47                 2.48       -11.80
48                 2.48       -20.02
49                 2.44       -24.93

In [11]:
# predicting resultant frequency and return loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
# from sklearn import tree
a_train,a_test,b_train,b_test = train_test_split(a,b,test_size=0.2)
model=LinearRegression()
model.fit(a_train,b_train)
p = model.predict(a_test)
print(a_test,p)
# tree.export_graphviz(model, out_file='ant-rec.dot',feature_names=['P1','P2','P3','P4','P5'],class_names = sorted(y.unique()),label='all',rounded=True,filled=True)
mse = mean_squared_error(b_test, p)
mse

       P1     P2     P3    P4     P5
32  27.94  58.50  58.89  0.25  2.270
6   46.57  58.50  44.17  0.75  3.030
28  33.53  45.94  53.89  0.50  5.980
36  27.94  45.94  49.39  0.75  7.470
44  22.35  40.35  40.39  0.50  8.220
25  33.53  62.71  44.89  0.75  8.220
49  18.63  23.40  39.26  0.25  1.515
37  27.94  40.35  44.89  0.25  6.720
35  27.94  46.80  53.83  0.75  1.515
1   55.89  58.50  49.07  0.37  1.515 [[  1.96563981 -15.30653306]
 [  2.83079116 -15.46255667]
 [  2.46414369 -15.74120658]
 [  2.861627   -13.11283626]
 [  3.02564936 -13.30932746]
 [  3.07366602 -11.66232631]
 [  2.54010813 -17.09534069]
 [  2.62767556 -15.93964774]
 [  2.42117721 -14.39942605]
 [  2.32842272 -19.35627047]]


29.934997239170443

In [68]:
# predicting resultant frequency and return loss with auto generated input parameters and 20% of train data
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
a_train,a_test,b_train,b_test = train_test_split(a,b,test_size=0.2)
model=LinearRegression()
model.fit(a_train,b_train)
p1 = model.predict(a_test)
mse = mean_squared_error(b_test, p1)
print(mse)
p = model.predict([[17,20,38,0.2,1.5],
                   [18,19,35,0.3,1.6],
                  [16,18,37,0.2,1.4],
                  [17.5,19.5,36,0.3,1.45],
                  [16.5,20,36.5,0.25,1.55]])
p

63.099183503541546


C:\Users\Sarthak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[  2.53450653, -18.42156267],
       [  2.70753672, -17.64412376],
       [  2.55988773, -18.37916051],
       [  2.66834926, -17.61045465],
       [  2.61681957, -17.72457843]])

In [33]:
# predicting optimal input parameters from output parameters given
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
b_train,b_test,a_train,a_test = train_test_split(b,a,test_size=0.2)
model=LinearRegression()
model.fit(b,a)
p = model.predict([[2.45,-30]])
p

C:\Users\Sarthak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[40.90966605, 43.42360274, 50.7665342 ,  0.43501478,  3.60343715]])

In [34]:
# predicting optimal input parameters from output parameters given (auto generated)
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
b_train,b_test,a_train,a_test = train_test_split(b,a,test_size=0.2)
model=LinearRegression()
model.fit(b_train,a_train)
p = model.predict(b_test)
print(b_test,p)

    Resultant Frequency  Return Loss
11                 2.43       -19.72
10                 2.43       -22.46
25                 2.48        -7.53
1                  2.58       -10.89
18                 2.54        -3.49
31                 4.91       -34.12
41                 2.53        -5.15
27                 2.57        -2.80
45                 2.58       -12.70
32                 2.40       -29.32 [[37.87319725 44.0590183  47.9813922   0.49590158  4.30446369]
 [39.09625467 42.54517607 48.21605687  0.48969298  4.05702096]
 [32.352331   50.88041422 46.74732023  0.52449199  5.4735917 ]
 [33.69293892 49.19693469 46.65494194  0.51881642  5.30671583]
 [30.45347104 53.21624934 46.17323295  0.53480901  5.9203688 ]
 [40.35279135 40.39125044 39.78713837  0.51133227  6.3906621 ]
 [31.2103674  52.28181295 46.35341628  0.53085381  5.75680248]
 [30.09771492 53.64934566 46.00009589  0.53695386  6.02364829]
 [34.50087101 48.19691482 46.80995766  0.51471512  5.14325914]
 [42.20612183 38.70317223 

In [7]:
#freq:2.45 gain:-30